-- Stephen Greer
DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME TEXT,
    USER_ROLE TEXT
);

DROP TABLE IF EXISTS SHOW;
CREATE TABLE SHOW(
    SHOW_ID INT PRIMARY KEY AUTO_INCREMENT,
    SHOW_TITLE TEXT,
    SHOW_DESC TEXT,
    SHOW_NUM_EP INT,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

DROP TABLE IF EXISTS WATCHING;
CREATE TABLE WATCHING(
    WATCHING_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    SHOW_ID INT,
    EPISODES_WATCHED INT,
    RATING INT,

    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY(SHOW_ID) REFERENCES SHOW(SHOW_ID)
);